# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06de7ade268584b72b0ed403ba169604d52884cab3d6b958c585d1ef18a33d804f3aea358b63dc6c02d80aa7add91b6010a53cbc0c8c5e5ca3eecec277f893e5

test:
  secret_key_base: 1cabeb37c9ee8b3345c230d83a734c15a7c7e48c6ab05f14c435ece6027f6d9123c12a448c9f8adf63085208c23948edd409e6efb872cc126d4f3c4f662eb31c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
